apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc-nfs-storage
  labels:
    app: jenkins
spec:
  storageClassName: managed-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi