apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-storage
  namespace: jenkins
  labels:
    type: nfs
spec:
  storageClassName: managed-nfs
  capacity:
    storage: 12Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.42.69.51
    path: "/opt/jenkins"