apiVersion: v1
kind: Service
metadata:
  name: postgres
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '5432'
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 55432
  selector:
    app: postgres