apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-nfs-storage
  labels:
    app: postgres
spec:
  storageClassName: managed-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16384Mi