apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-nfs-storage
  labels:
    type: nfs
spec:
  storageClassName: managed-nfs
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.42.69.51
    path: "/opt/postgres"